import { Bot, Mail, MailX, TrendingUp, TriangleAlert } from 'lucide-react';

import Card from '../../components/Card';
import { StatusBadge } from '../../components/StatusBadge';
import { ErrorState, SkeletonList } from '../../components/States';
import { useLatestRecommendation } from '../../hooks/useDecisions';
import { useNotifications } from '../../hooks/useAlerts';
import { formatMW, formatRelative, humanise } from '../../utils/format';
import { sortByImpact } from '../../utils/status';

/**
 * AI decisions card (plan §4.4).
 *
 * Surfaces the latest cron-generated classification (lower/usual/higher), the
 * Decision Agent's recommended action, and any high-alert / sensor-failure
 * escalations. Email dispatch is backend-only, so notifications are shown
 * read-only — including when a send was skipped because SMTP is unconfigured.
 */
export default function AiDecisionCard({ plantId, performance, performanceQuery, className = '' }) {
  const recommendation = useLatestRecommendation(plantId);
  const notifications = useNotifications({ plantId, limit: 5 });

  const reasons = sortByImpact(performance?.reasons || []);
  const escalations = (notifications.data?.notifications || []).filter(
    (n) => n.channel === 'email',
  );
  const emailConfigured = notifications.data?.emailConfigured;

  return (
    <Card
      title="AI decision"
      subtitle={
        performance?.forecastGeneratedAt
          ? `Scheduled forecast ${formatRelative(performance.forecastGeneratedAt)}`
          : 'Generated by the scheduled forecast run'
      }
      icon={Bot}
      className={className}
      bodyClassName="space-y-3 overflow-y-auto p-4"
    >
      {performanceQuery?.isLoading && <SkeletonList rows={2} />}

      {performanceQuery?.isError && (
        <ErrorState
          error={performanceQuery.error}
          onRetry={performanceQuery.refetch}
          title="Could not load the AI assessment"
          compact
        />
      )}

      {performance && (
        <>
          {/* Classification against the cron forecast */}
          <div className="space-y-2.5 rounded-[3px] border border-line bg-surface p-3">
            <div className="flex items-center justify-between gap-2">
              <span className="fc-label text-ink-muted">Output vs prediction</span>
              <StatusBadge
                classification={performance.classification}
                deltaPct={performance.deltaPct}
              />
            </div>
            <dl className="grid grid-cols-2 gap-2">
              <div>
                <dt className="fc-label text-ink-muted">Measured</dt>
                <dd className="mt-1 font-mono text-base text-ink">
                  {formatMW(performance.actualMW)}
                </dd>
              </div>
              <div>
                <dt className="fc-label text-ink-muted">Predicted</dt>
                <dd className="mt-1 font-mono text-base text-ink">
                  {formatMW(performance.expectedMW)}
                </dd>
              </div>
            </dl>
            {performance.confidencePct !== null && performance.confidencePct !== undefined && (
              <p className="font-mono text-[11px] text-ink-muted">
                Prediction confidence {performance.confidencePct}%
              </p>
            )}
          </div>

          {/* Attributed causes */}
          {reasons.length > 0 && (
            <div className="space-y-2">
              <h3 className="fc-label text-ink">Contributing factors</h3>
              <ul className="space-y-1.5">
                {reasons.map((reason) => {
                  // The same reason list explains shortfalls and overshoots —
                  // a warning triangle would misread an overshoot as a fault.
                  const isPositive = performance.classification === 'higher';
                  const Icon = isPositive ? TrendingUp : TriangleAlert;
                  const tone = isPositive
                    ? 'text-status-higher'
                    : reason.impact === 'high'
                      ? 'text-severity-high'
                      : 'text-severity-medium';

                  return (
                    <li
                      key={reason.code}
                      className="rounded-[3px] border border-line bg-surface-raised p-2.5"
                    >
                      <div className="flex items-start gap-1.5">
                        <Icon className={`mt-0.5 size-3.5 shrink-0 ${tone}`} aria-hidden="true" />
                        <div>
                          <p className="fc-label text-ink">{humanise(reason.code)}</p>
                          <p className="text-xs text-ink-muted">{reason.detail}</p>
                        </div>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </div>
          )}
        </>
      )}

      {/* Recommended grid action */}
      <div className="space-y-2.5 border-t border-line pt-3">
        <h3 className="fc-label text-ink">Recommended action</h3>

        {recommendation.isLoading && <SkeletonList rows={1} />}

        {recommendation.isError && recommendation.error?.status === 404 && (
          <p className="text-xs text-ink-muted">
            No recommendation yet — the Decision Agent runs with each scheduled forecast.
          </p>
        )}

        {recommendation.isError && recommendation.error?.status !== 404 && (
          <ErrorState error={recommendation.error} onRetry={recommendation.refetch} compact />
        )}

        {recommendation.data && (
          <div className="rounded-[3px] border border-brand/30 bg-severity-low-soft p-3">
            <p className="font-mono text-sm tracking-[0.04em] text-brand-dark uppercase">
              {humanise(recommendation.data.action)}
              {recommendation.data.amountMW ? ` · ${formatMW(recommendation.data.amountMW)}` : ''}
              {recommendation.data.durationHours
                ? ` for ${recommendation.data.durationHours}h`
                : ''}
            </p>
            <p className="mt-1 text-xs text-ink">{recommendation.data.reasoning}</p>
            <p className="mt-2 font-mono text-[11px] text-ink-muted">
              {formatRelative(recommendation.data.generatedAt)}
            </p>
          </div>
        )}
      </div>

      {/* Notification escalations — display only */}
      <div className="space-y-2.5 border-t border-line pt-3">
        <h3 className="fc-label flex items-center gap-2 text-ink">
          {emailConfigured ? (
            <Mail className="size-3.5 text-ink-muted" aria-hidden="true" />
          ) : (
            <MailX className="size-3.5 text-ink-muted" aria-hidden="true" />
          )}
          Email escalations
        </h3>

        {emailConfigured === false && (
          <p className="text-xs text-ink-muted">
            SMTP is not configured, so high-severity and sensor-fault alerts are logged but not
            emailed.
          </p>
        )}

        {escalations.length === 0 ? (
          <p className="text-xs text-ink-muted">No escalations raised for this plant.</p>
        ) : (
          <ul className="space-y-1.5">
            {escalations.map((note) => (
              <li key={note.id} className="flex items-start justify-between gap-2 text-xs">
                <span className="min-w-0 text-ink">
                  {humanise(note.type)}
                  <span className="font-mono text-[11px] text-ink-muted">
                    {' '}
                    · {formatRelative(note.createdAt)}
                  </span>
                </span>
                <span
                  className={`fc-label shrink-0 rounded-[2px] px-1.5 py-0.5 ${
                    note.status === 'sent'
                      ? 'bg-status-usual-soft text-status-usual'
                      : note.status === 'failed'
                        ? 'bg-severity-high-soft text-severity-high'
                        : 'bg-surface text-ink-muted'
                  }`}
                >
                  {note.status}
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </Card>
  );
}
