/**
 * Runtime configuration and the polling cadence for every live widget.
 *
 * Intervals live here (rather than scattered through hooks) so the real-time
 * strategy can be reviewed in one place — see API_CONTRACT.md.
 */

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/v1';
export const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || 'http://localhost:5000';

export const POLL_INTERVALS = {
  /** Telemetry lands hourly; 30s keeps the reading fresh without hammering Mongo. */
  liveGeneration: 30_000,
  /** Same cadence as generation — they are read together on the dashboard. */
  performance: 30_000,
  /** Backs up the Socket.IO push in case the socket drops. */
  alerts: 20_000,
  /** Server caches weather for 60 min, so anything tighter is wasted. */
  weather: 5 * 60_000,
  /** Regenerated by the hourly forecast cron. */
  forecast: 5 * 60_000,
  recommendation: 5 * 60_000,
  /** Only changes when an alert fires. */
  notifications: 60_000,
};

/** React Query defaults — deliberately conservative for a control-room UI. */
export const QUERY_DEFAULTS = {
  /** Data is considered fresh for 15s; avoids refetch storms on remount. */
  staleTime: 15_000,
  /** One retry: a genuinely down backend should surface fast, not hang. */
  retry: 1,
  retryDelay: 1_000,
  refetchOnWindowFocus: true,
};
